<?php echo $this->doctype('XHTML1_STRICT') ?>
<html>
	<head>
	<?php echo $this->block('pages/element/header', 'pages/elements/header.phtml') ?>
	</head>
<body>
	<div>
		<?php echo $this->block('pages/element', 'pages/elements/top.phtml') ?>
		<div style="background-color:green;width:100%;height:3000px">
			<?php echo $content ?>
		</div>
		<?php echo $this->block('pages/element', 'pages/elements/footer.phtml') ?>
	</div>
</body>
</html>